### ISSUE TITLE
Can't open mod config and crash

### ISSUE THREAD

**Issue by Lcat12345** [MaiKokain/StackUpper#1]
The game crashed whilst mouseclicked event handler
Error: java.lang.AbstractMethodError: Receiver class yuria.stackupper.StackUpper$$Lambda/0x0000000800faf8b8 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.client.gui.screens.Screen createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)' of interface net.neoforged.neoforge.client.gui.IConfigScreenFactory.

**Comment by Lcat12345** [comment]
> The game crashed whilst mouseclicked event handler Error: java.lang.AbstractMethodError: Receiver class yuria.stackupper.StackUpper$$Lambda/0x0000000800faf8b8 does not define or inherit an implementation of the resolved method 'abstract net.minecraft.client.gui.screens.Screen createScreen(net.neoforged.fml.ModContainer, net.minecraft.client.gui.screens.Screen)' of interface net.neoforged.neoforge.client.gui.IConfigScreenFactory.

**Comment by MaiKokain** [comment]
Provide your minecraft and neoforge version and do you have any other mods installed also if possible send either the debug.log file or the crash log file.

**Comment by Lcat12345** [comment]
thank you to check!

minecraft version : 1.21
neoforge version : neoforge-21.0.163

[debug.log](https://github.com/user-attachments/files/16568353/debug.log)
[crash-2024-08-10_12.50.03-client.txt](https://github.com/user-attachments/files/16568354/crash-2024-08-10_12.50.03-client.txt)

**Comment by MaiKokain** [comment]
Fixed. update StackUpper to 1.0.2.
