### ISSUE TITLE
Compatibility errors

### ISSUE THREAD

**Issue by askajdiw** [MaiKokain/StackUpper#2]
Using it with the Bigger Stack Size（https://modrinth.com/datapack/bigger-stack-size） causes the item to stack to 64

**Comment by MaiKokain** [comment]
I don't know why you're using the "bigger-stack-size" datapack with this mod, since it does all of that already except for tools. but have you tried configuring stackupper.

**Comment by askajdiw** [comment]
> 我不知道你为什么在这个 mod 中使用“bigger-stack-size”数据包，因为这个 mod 已经完成了除了工具之外的所有工作，但你有没有尝试过配置 stackupper。

What if I want to configure separate items (e.g. Totem of the undying)

**Comment by MaiKokain** [comment]
> > 我不知道你为什么在这个 mod 中使用“bigger-stack-size”数据包，因为这个 mod 已经完成了除了工具之外的所有工作，但你有没有尝试过配置 stackupper。
> 
> What if I want to configure separate items (e.g. Totem of the undying)

i guess that makes sense since stackupper ignore item that has stack size of 1 and set every item stack size to the configured amount, i am planning to add scripting support but haven't gotten around working with ANTLR, I'll try to figure out it isn't working with the datapack or maybe just do an alternative method.

**Comment by MaiKokain** [comment]
> Using it with the Bigger Stack Size（[https://modrinth.com/datapack/bigger-stack-size）](https://modrinth.com/datapack/bigger-stack-size%EF%BC%89) causes the item to stack to 64

Works as expected, and this isn't even a compatibility issue, even changing stackupper maxStack applies to the datapack.

![Inventory Image](https://github.com/user-attachments/assets/b467175d-701f-4be9-95d2-a9cff7a93f84)
![StackUpper Config Image](https://github.com/user-attachments/assets/6d35d4bd-544c-4256-b2ff-827c2c39f02d)
![Inventory Image 2 (stack over 127)](https://github.com/user-attachments/assets/b6a75732-49b1-4b48-8710-41cbe8ac8e72)
