### ISSUE TITLE
Stack Bugged

### ISSUE THREAD

**Issue by montana255** [MaiKokain/StackUpper#3]
I edit the number of stacks and make it 100k, when I buy 100k items and put them in the chest, the stack numbers are broken in a row.

For example: I put 100k items in the chest, the chest shows strange numbers like 90k 50k 1k.

And when I take things back from the crate, they don't come together.

![image](https://github.com/user-attachments/assets/f4585cf0-6841-4294-b79f-309126bd70f1)

![image](https://github.com/user-attachments/assets/cd907efa-2f19-4d81-8f9b-ed59fcdb3f9c)

![image](https://github.com/user-attachments/assets/6b581883-2534-4ac8-9096-58379701dd76)

![image](https://github.com/user-attachments/assets/720d8233-b600-44da-be52-6340ac74babb)

![image](https://github.com/user-attachments/assets/d9949eba-fd76-4401-b710-8ada8bde10ce)

As it looks in the pictures.

Finally, the game crashes as soon as I increase the number of stacks above 100k.

![image](https://github.com/user-attachments/assets/8e00c38f-9085-48a2-b73c-f09e2ddb77b4)

**Comment by MaiKokain** [comment]
Hi, thanks for the report.

- Changing config then crashes
  - This is already known, relaunch Minecraft and it would take effect.
 
As for the container could you give more details. It rendering shortened text is a feature not a bug, do you mean it shows the wrong amount in the truncated version? and another when you take things from the container does it not stack together to the amount (100k)?

**Comment by montana255** [comment]
> Hi, thanks for the report.
> 
> * Changing config then crashes
>   
>   * This is already known, relaunch Minecraft and it would take effect.
> 
> As for the container could you give more details. It rendering shortened text is a feature not a bug, do you mean it shows the wrong amount in the truncated version? and another when you take things from the container does it not stack together to the amount (100k)?

I showed it completely in the video.
https://youtu.be/ndIMO7O2sgw

**Comment by MaiKokain** [comment]
> > Hi, thanks for the report.
> > 
> > * Changing config then crashes
> >   
> >   * This is already known, relaunch Minecraft and it would take effect.
> > 
> > As for the container could you give more details. It rendering shortened text is a feature not a bug, do you mean it shows the wrong amount in the truncated version? and another when you take things from the container does it not stack together to the amount (100k)?
> 
> I showed it completely in the video. https://youtu.be/ndIMO7O2sgw

Could you provide all the mods you used, i had no issues with containers.

Video: https://streamable.com/jz9cfa
