### ISSUE TITLE
No Configs for v2.00 and v2.0.1

### ISSUE THREAD

**Issue by iAroc** [MaiKokain/StackUpper#4]
Heya.

Im on 1.21.1 Neoforge, and when installing Stackupper, it installs Version 2.0.1, since that is marked as the newest.

But on that Version (and on 2.0.0) i dont have the option to edit the max stacks. Like on Version 1.0.4, i can click on Config in the Mod-Lists and edit the max-stack Value.

Did the Config move somewhere else in the new Versions, or is this just broken?

**Comment by MaiKokain** [comment]
hi, i don't think you've read the update log but the newer version (from 2.0.x), i used a scripting system instead of applying to all item that is able to stack higher than 1.

check out the wiki, or create a file in `config/stackupper/` that ends with `su` or `stackupper` and put the content below. replace `NUMBER` with the amount you want it to be.
```
size < 1 -> NUMBER
```

if this does become an issue with a lot of users, i might add back the config

**Comment by itsryzor** [comment]
I have the same issue. The mod does nothing by default, and applying the above script config only adjusts the max stack size to 99 rather than the 1 million I put down as a test.

**Comment by iAroc** [comment]
i mean it sounds good if ppl sont want to have higher stacks on everything, but as a normal player that just wants more stacks.. i just downgraded to 1.0.4 and input my prefer'd stacksize there.

i mean how do you except a user that just downloads the mod to find the wiki to it, and understand how he has to create files on its own for every item there is, just so he then gets more stacks. that is a neat feature for advanced users, but i prefer the easy solution.


also your description on curseforge doesnt tell anything about scripting and creating files :/

**Comment by MaiKokain** [comment]
> I have the same issue. The mod does nothing by default, and applying the above script config only adjusts the max stack size to 99 rather than the 1 million I put down as a test.
> 
> Edit: version 1.04 works absolutely normally after changing the config with Configured. I will be using that for now.

if it only max to 99 why didn't you open another issue, also that may be your own skill issue since i literally used it on `All the Mods 10` with no issues.

**Comment by MaiKokain** [comment]
Update to version `2.0.2` for any further problems or errors, open a new issue.

Modrinth: https://modrinth.com/mod/stackupper/version/2.0.2
CurseForge: https://www.curseforge.com/minecraft/mc-mods/stackupper/files/all
